objects/BIN_Address_Asset_Entitlement__mdt.object
<CustomObject>
    <fields>
        <fullName>Bin_Colour__c</fullName>
        <label>Bin Colour</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Red</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Lime Green</fullName>
                </value>
                <value>
                    <fullName>Bulky</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bin_Purpose__c</fullName>
        <label>Bin Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Garbage</fullName>
                    <default>true</default>
                    <label>Garbage</label>
                </value>
                <value>
                    <fullName>Recycling</fullName>
                </value>
                <value>
                    <fullName>Organics</fullName>
                </value>
                <value>
                    <fullName>FOGO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bin_Size__c</fullName>
        <label>Bin Size</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>140L</fullName>
                </value>
                <value>
                    <fullName>2000L</fullName>
                </value>
                <value>
                    <fullName>240L</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bin_Type__c</fullName>
        <label>Bin Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hopper</fullName>
                    <default>true</default>
                    <label>Hopper</label>
                </value>
                <value>
                    <fullName>MGB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_New_Set_Bin__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will inform if this bin entitlement will be considered for delivery of New Set of bins.</description>
        <label>Is New Set Bin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Land_Use_Code__c</fullName>
        <label>Land Use Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>This is Related to Bins project.</description>
    <label>BIN Address Asset Entitlement</label>
    <pluralLabel>BIN Address Asset Entitlements</pluralLabel>
</CustomObject>

objects/CORE_Address__c.object
<CustomObject>
    <fields>
        <fullName>Land_Use_Code__c</fullName>
        <label>Land Use Code</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostCode__c</fullName>
        <label>PostCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Unit Number + Street Number + Door Number + Road Name</description>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Number__c</fullName>
        <label>Street Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suburb_Name__c</fullName>
        <label>Suburb Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <label>Unit Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>CORE Address</label>
    <nameField>
        <label>Core Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CORE Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BIN_CoreAddressDAO.cls
/**
* @author Pryscilla Nascimento – ProQuest It
* @date 11/11/2019
*
* @group Address
* @group-content ../../ApexDocContent/BinUtils.htm
*
* @description Util Methods for Address (Core_Address__c) Related Information
**/
public with sharing class BIN_CoreAddressDAO {

    /**
    * @description Returns a list of Core_Address__c using SOSL
    * @param searchKey the search term 
    * @return the list of core addressses in the system that matches the search term
    */
    @AuraEnabled(cacheable = true)
    public static Core_Address__c[] getAddresses(String searchKey){

        if(String.isEmpty(searchKey))
            return new Core_Address__c[]{};

        searchKey = String.escapeSingleQuotes(searchKey);

        String query =  ' FIND \''+searchKey+'*\' IN ALL FIELDS ' + 
                        ' RETURNING Core_Address__c (' +
                        '   Id, ' +
                        '   Street_Address__c, ' +
                        '   Suburb_Name__c, ' +
                        '   PostCode__c, ' +
                        '   Land_Use_Code__c ' +
                        ' ORDER BY Suburb_Name__c, Street_Name__c, Unit_Number__c, Street_Number__c )';

        system.debug('query----' + query);

        List<List<SObject>> addressResult = search.query(query);

        return (Core_Address__c[]) addressResult[0];
    }

    /**
    * @description Returns the New Bins Set entitlements for an address land use code
    * @param landUseCode the land use code 
    * @return the list of New Bins Set entitlements (quantity, bin colour and size) given the land use code and Is_New_Set_Bin__c = true
    */
    @AuraEnabled(cacheable = true)
    public static list<BIN_Address_Asset_Entitlement__mdt> getNewBinSetEntitlements(String landUseCode){

        return [SELECT  Bin_Colour__c, 
                        Bin_Size__c, 
                        Quantity__c,
                        Bin_Type__c, 
                        Bin_Purpose__c 
                FROM    BIN_Address_Asset_Entitlement__mdt 
                WHERE   Land_Use_Code__c = :landUseCode AND
                        Is_New_Set_Bin__c = true
                ORDER BY Bin_Colour__c];
    }

}