objects/Case.object
<CustomObject>
    <fields>
        <fullName>BIN_Service_Request_Number__c</fullName>
        <displayFormat>SR{000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>CORE_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>CORE_Address__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CORE_Address__c.object
<CustomObject>
    <label>CORE Address</label>
    <nameField>
        <label>Core Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CORE Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BIN_ServiceRequestDAOTest.cls
@isTest
private class BIN_ServiceRequestDAOTest {

    @testSetup static void setup() {
        // List<sObject> coreAddresssess = Test.loadData(CORE_Address__c.sObjectType, 'bin_Core_Address_TestData');

        Database.insert(new Case());
      
    }

    @isTest 
    private static void testGetRequestNumber(){

        //Test Positive Scenario
        Case serviceRequest = [ SELECT ID 
                                FROM Case limit 1];

        Case result = BIN_ServiceRequestDAO.getRequestNumber(serviceRequest.Id);
        System.AssertNotEquals( result.BIN_Service_Request_Number__c , null );



        //Test Negative Scenario (null Id)
        result = BIN_ServiceRequestDAO.getRequestNumber(null);
        System.AssertEquals( result.BIN_Service_Request_Number__c , null );
    }

  

}